### ISSUE TITLE
Getting error while activating plugin

### ISSUE THREAD

**Issue by Broyojo** [fenix-hub/godot-engine.github-integration#26]
Here is the error message I get when I activate the GitHub integration plugin:

 res://addons/github-integration/scripts/SignIn.gd:49 - Invalid call. Nonexistent function 'load_user' in base 'Node (user_data.gd)'.

**Comment by fenix-hub** [comment]
Hi,
Please, can you provide more informations about the issue to let me work better on it?
Godot Engine version and Plugin version would be appreciated.

**Comment by Broyojo** [comment]
Okay no problem! I am using Godot version 3.1.1 (this might be an older version which might be the problem) and the plugin version is 0.3.2

**Comment by fenix-hub** [comment]
Hi,
Thank you very much for the informations.
As I imagined, the plugin is not updated to the latest version for >3.1.2 versions of Godot in the AssetLibrary.
I'm going to upload the latest version right now.
Please, in the meantime, clone this plugin from the source code directly from the master branch [here](https://github.com/fenix-hub/godot-engine.github-integration.git), delete the older version of the plugin from your project, and let me now if it works fine.

**Comment by fenix-hub** [comment]
Feel free to open new issues if something doesn't work.
