### ISSUE TITLE
Everything's busted :/

### ISSUE THREAD

**Issue by SIsilicon** [fenix-hub/godot-engine.github-integration#34]
Godot: *3.2 stable*
Plugin: *0.8.0*

Nothing happens when I press that exclamation mark in the sign in area. In fact, none of the buttons seem to do anything either.

Also the console printed following errors.

res://addons/github-integration/scripts/SignIn.gd:36 - Parse Error: The identifier "UserData" isn't declared in the current scope.
 modules/gdscript/gdscript.cpp:576 - Method failed. Returning: ERR_PARSE_ERROR
 res://addons/github-integration/scripts/UserPanel.gd:41 - Parse Error: The identifier "UserData" isn't declared in the current scope.
 modules/gdscript/gdscript.cpp:576 - Method failed. Returning: ERR_PARSE_ERROR
 res://addons/github-integration/scripts/Repo.gd:107 - Parse Error: The identifier "IconLoaderGithub" isn't declared in the current scope.
 modules/gdscript/gdscript.cpp:576 - Method failed. Returning: ERR_PARSE_ERROR
 res://addons/github-integration/scripts/Commit.gd:209 - Parse Error: The identifier "UserData" isn't declared in the current scope.
 modules/gdscript/gdscript.cpp:576 - Method failed. Returning: ERR_PARSE_ERROR
 res://addons/github-integration/scripts/WindowDialog.gd:99 - Parse Error: The identifier "UserData" isn't declared in the current scope.
 modules/gdscript/gdscript.cpp:576 - Method failed. Returning: ERR_PARSE_ERROR
 res://addons/github-integration/scripts/Gist.gd:66 - Parse Error: The identifier "IconLoaderGithub" isn't declared in the current scope.
 modules/gdscript/gdscript.cpp:576 - Method failed. Returning: ERR_PARSE_ERROR
 Failed to get modified time for: C:/Users/Student/Documents/Godot Projects/Code Cube/addons/file-editor/fonts/Roboto-Black.ttf.
 Cannot open font file 'res://addons/file-editor/fonts/Roboto-Black.ttf'.

**Comment by fenix-hub** [comment]
Hi @SIsilicon ,
The v0.8.0 should be intended to work with Godot v3.2-RC2.
Also, if you installed it from AssetLibrary, I'm pretty sure it is not getting the right version.
I didn't had the time to update it for the 3.2stable version yet, but I'm going to make a quick release later.
You will find it as v0.8.1 directly posted here. 
Please, disable the plugin and delete the "res://addon" folder before installing the new plugin version.
Also, pull it directly from my repository when it will be available, since you won't find it in the Asset Library yet.

PS. The exclamation mark is not a button, it just pops out if you already have a log file on your computer.

**Comment by fenix-hub** [comment]
Hello,
#35 should fix those bugs.
I'm not currently able to do some tests, but you can just try and use this issue to tell me if everything is fine or not

**Comment by SIsilicon** [comment]
Great! I'll check it out tomorrow. 👍

**Comment by SIsilicon** [comment]
Okay, so I tried it today, but it's saying `Error: Bad credentials`. I triple checked the username and password, and have also tried signing in with those same settings here on GitHub.

This is what printed out in the console.
```
[GitHub integration] >> logging in...
* [GitHub integration] >> Bad credentials - incorrect username or token.
```

**Comment by fenix-hub** [comment]
You need to access with username and token , as specified in Field's labels
. You can create a token with the button under the token field.


Il sab 1 feb 2020, 21:17 Roujel Williams <notifications@github.com> ha
scritto:

**Comment by SIsilicon** [comment]
Okay. It's working now.
Thank you for your patience. Tokens are new to me.

**Comment by fenix-hub** [comment]
Perfect, I'll close the issue then.
Thank you very much for your feedback, if you find any bug don't hesitate
to open a new issue.


Il sab 1 feb 2020, 21:47 Roujel Williams <notifications@github.com> ha
scritto:
