### ISSUE TITLE
Github login infinite loading

### ISSUE THREAD

**Issue by Belgianix** [fenix-hub/godot-engine.github-integration#44]
The login will keep displaying the login progress emblem without ever logging in
![image](https://user-images.githubusercontent.com/62674041/83276975-697ea180-a19f-11ea-8eba-f62d719ee90e.png)

**Comment by fenix-hub** [comment]
Hello @Belgianix ,
can you please provide me your Godot version?
Could you also take a screenshot/paste the messages printed in the output console from the plugin?

Thank you.

**Comment by Belgianix** [comment]
Sorry for the late reply but I'm currently running V3.2.1. Below is the screen and terminal which it gets stuck at
![ScreenShot_20200602004554](https://user-images.githubusercontent.com/62674041/83480999-ac27ce80-a46a-11ea-9357-2f6350cc1359.png)

**Comment by fenix-hub** [comment]
@Belgianix Don't worry about the delay in replying.
The plugin is currently being developed and supporting Godot Engine 3.2.2, but anyway I can't  reproduce the issue you are having.
Have you tried downloading the latest plugin version?

**Comment by ghost** [comment]
@Belgianix I had that problem and all I did is to open a new project and install it there, it worked great, hope that helps you aswell

**Comment by fenix-hub** [comment]
#46 I'll mark this as resolved.
