### ISSUE TITLE
GitHub Integration loading never completes

### ISSUE THREAD

**Issue by ghost** [fenix-hub/godot-engine.github-integration#46]
Godot: 3.2.1
Plugin: 0.8.7

After installation, when I try to log in the plugin loads forever and it displays <logfile.mail> for some reason, but the main problem is that it never finishes

https://user-images.githubusercontent.com/66429843/83774337-3e5bec80-a68e-11ea-8865-3b2ff50336fe.png

**Comment by fenix-hub** [comment]
Hi @ELZURIX ,
I tried to test the plugin both on 3.2.1 and 3.2.2 but couldn't reproduce the error.
Have you ever logged in before? Or it is the first time you try to log in?
Are you using your email and token?
Also, what's your OS?
Also, I can't see any message in the debug console. 
After you try to log in, try to catch some messages from the plugin itself, they always start with a tag `[GitHub Integration]`

**Comment by ghost** [comment]
I'm using windows, and yes I'm using my email and the token from the "Developer settings" option in GitHub and I enabled all the permissions in the token settings so that your plugin will be able to affect the stuff
I tried to log in before and it worked once but after that, it didn't work anymore
The only error I caught when I logged in is the "error opening file" one but I don't think that the icon is that necessary
![2020-06-05_15-53-40](https://user-images.githubusercontent.com/66429843/83878374-c13f7e80-a744-11ea-92c6-42e42a6a7091.png)

**Comment by fenix-hub** [comment]
Hi,
the error with the avatar shouldn't interfere with the login process.
Tested on both 3.2.1 and 3.2.2 and the login is ok.
I can't seem to find any other related issue, and there are no important errors in output.
The API connects successfully and the login starts with no errors.

The only thing I can suggest you is to go to your user:// folder and delete your datas.
To do so, open a project and go to `Project > Open Project Data Folder > Back to Godot folder (there should be 2 folder distance, so travel back for 2 folders) > github_integration` and delete `user_data.ud` and `avatar.png`

**Comment by ghost** [comment]
Okay, for some reason it was only this project that it didn't work in, I tried it in another project and it worked just fine, this is weird, but still, I think I can move all the scenes and assets to a new folder and that's it, thanks for the help! :)

**Comment by fenix-hub** [comment]
Hi,
I'm happy you resolved your issue.
Thank you for using my plugin, I hope you will find it useful :)
Have a nice one, for any problem don't hesitate to open a new issue or contact me.
