### ISSUE TITLE
Add Delete Logfile data?

### ISSUE THREAD

**Issue by venska** [fenix-hub/godot-engine.github-integration#49]
Godot: *3.2.1*
Plugin: *0.9.0*

Add a button to delete past logfiles
 If someone had forgotten the token, and had to regenerate the token, the plugin seems like to always use the old token from logfiles. Or perhaps it's an isolated issue on my behalf? Please let me know as I'm not sure.
Also logfile is misspelled when hovering over the exclamation point. :-)

**Comment by fenix-hub** [comment]
Hi @venska ,
Commit 398a7b9c8e69d76246175630b8fe42bdab544114 adds a new functionality to the Sign In screen:

![Godot_v3 2 1-stable_mono_win64_fUDQHUWtj0](https://user-images.githubusercontent.com/45271396/85226075-d1f32400-b3d5-11ea-81b8-6df45be8a0d0.png)
![Godot_v3 2 1-stable_mono_win64_Pfv8GeTNZG](https://user-images.githubusercontent.com/45271396/85226078-d4557e00-b3d5-11ea-95f4-7d31ecceb098.png)

Also fixed "logfile" misspelling.
Thank you very much
