### ISSUE TITLE
Remove batch files from commit file selection

### ISSUE THREAD

**Issue by Bobstar89** [fenix-hub/godot-engine.github-integration#51]
**Godot Version & Plugin Version**
Godot: *3.2.1*
Plugin: *0.9.0*

**Describe the bug**
When making a commit to a repository, the plugin user cannot select multiple files when removing files from the "Committing files" column

**Screenshots**
<img width="634" alt="Screen Shot 2020-06-24 at 11 56 31 am" src="https://user-images.githubusercontent.com/24449191/85488525-cb50f080-b611-11ea-9bfa-e72946f05106.png">

**Comment by fenix-hub** [comment]
Hi @Bobstar89 
Commit 06a4ea012c18e0991c002631193d2482fb29db35 implements this feature.
Let me know if you encounter any problem, I'll leave this issue opened.
