### ISSUE TITLE
Cannot save project in sub folder in repository

### ISSUE THREAD

**Issue by Bobstar89** [fenix-hub/godot-engine.github-integration#54]
**Godot Version & Plugin Version**
Godot: *3.2.1*
Plugin: *0.9.3*

**Describe the bug**
When viewing a repository, I would like to be able to save my project in a subfolder of my repository root

**Screenshots**

<img width="1252" alt="Screen Shot 2020-06-24 at 9 01 07 pm copy" src="https://user-images.githubusercontent.com/24449191/85545056-edbd2b00-b65e-11ea-946d-d3c0afab4c72.png">

<img width="1272" alt="Screen Shot 2020-06-24 at 8 55 43 pm copy" src="https://user-images.githubusercontent.com/24449191/85545089-f6adfc80-b65e-11ea-9903-8d82bbc7e528.png">

**Comment by fenix-hub** [comment]
Hi @Bobstar89 ,
That's not a bug, and anyway it is not something possible even with git.
To do something like that, you should just create the same tree in your project.
But it is just how git works in general, so I suggest you to check out some more informations on how git works if you are using it for the first time.
