### ISSUE TITLE
Importing files through commit file selection

### ISSUE THREAD

**Issue by Bobstar89** [fenix-hub/godot-engine.github-integration#55]
**Godot Version & Plugin Version**
Godot: *3.2.1*
Plugin: *0.9.3*

**Describe the bug**
Sometimes within the "COMMIT AND PUSH" window, files within a directory aren't successfully added to the "committing files" list

**Screenshots**
I have attached a zip with a video showing this effect

[Committing files.mov.zip](https://github.com/fenix-hub/godot-engine.github-integration/files/4825028/Committing.files.mov.zip)

**Comment by fenix-hub** [comment]
Hi @Bobstar89 ,
Thank you for committing this issue.
It clearly looks like something related to the newest multiple deletion feature.
I'll invastigate a little more and, as soon as I'll resolve it, I'll just update you with the latest version of the plugin.

A little reminder: the AssetLibrary is not updated automatically, and updates are not immediate. Always download the latest version you can find in this repository :)

**Comment by fenix-hub** [comment]
Closing with #58 ,
Will be reopened if needed.
