### ISSUE TITLE
Cannot Commit Files to New Repo

### ISSUE THREAD

**Issue by Bragendesh** [fenix-hub/godot-engine.github-integration#56]
**Godot Version & Plugin Version**
Godot: *3.2.1 stable official*
Plugin: *0.9.2*

**Describe the bug**
I created a new repo from within the integration tool. I entered that repo and clicked the "Commit to Repo" button. I selected the "res://" directory of an existing project and clicked on "Commit and Push". Everything is blobbed fine, but then I get an error from the API that a "new tree" cannot be processed. See the output below.

I also tried to pull from the branch and unzip first, but I got the same output.

**Output Log**
```
[GitHub integration] >> blobbed each file with success, start committing...
REQUEST TO API : Request exited with code 422
{documentation_url:https://developer.github.com/v3/git/trees/#create-a-tree, message:tree.path cannot start with a slash}
[GitHub integration] >> could not process the new tree, the file may be corrupted or already present in the repository without any changes.
REQUEST TO API : Request exited with code 422
{documentation_url:https://developer.github.com/v3/git/commits/#create-a-commit, message:Invalid request.

For 'properties/tree', nil is not a string.}
[GitHub integration] >> could not process the new commit, tree may be invalid.
REQUEST TO API : Request exited with code 422
{documentation_url:https://developer.github.com/v3, message:Invalid request.

For 'properties/sha', nil is not a string.}
```

**Comment by fenix-hub** [comment]
@Bragendesh 
Finally, next update will fix this issue. Everything will be ready this weekend.

**Comment by fenix-hub** [comment]
Closing with #58 
will be reopened if needed.
