### ISSUE TITLE
infinite loading screen

### ISSUE THREAD

**Issue by wooshings** [fenix-hub/godot-engine.github-integration#57]
**Godot Version & Plugin Version**
Godot: 3.2.1
Plugin: 0.9.2

**Describe the bug**
every time i try to maka a new repo or try to commit changes to an already existing repo i wind up with a never ending loading screen 

**Screenshots**
<img width="1235" alt="Screen Shot 2020-07-23 at 8 07 03 PM" src="https://user-images.githubusercontent.com/63532428/88357467-33cde300-cd20-11ea-9a67-e3ad579999cf.png">

**Comment by fenix-hub** [comment]
Hi @wooshdude ,
Could you please share what the console prints during the loading screen?
Thank you

**Comment by wooshings** [comment]
im not quite sure if this is what you're mentioning but

![Capture](https://user-images.githubusercontent.com/63532428/88423452-a9799380-cda0-11ea-875b-cf6ff855b99e.PNG)

**Comment by wooshings** [comment]
![image](https://user-images.githubusercontent.com/63532428/88434265-b1433300-cdb4-11ea-888d-32c9c0855dad.png)
this is what happens when i try to commit and push

**Comment by fenix-hub** [comment]
Thank you very much.
Next update should fix this issues.

**Comment by fenix-hub** [comment]
Closing with new version #58 ,
will be reopened if needed.
