### ISSUE TITLE
"Connecting to API" fails

### ISSUE THREAD

**Issue by D2klaas** [fenix-hub/godot-engine.github-integration#61]
**Godot Version & Plugin Version**
Godot: *3.2.2*
Plugin: *1.2.0*

**Describe the bug**
The console states "Connecting to API" and never resolves the connection. Login is then impossible.

When godot is busy loading the initial scene, the _ready() function of RestHandler is sometimes called after check_connection(). This shuts down _processing() and the Client.connect_to_host("www.githubstatus.com") is never resolved.
Deleting the set_process(false) in RestHandlers _ready() function fixes it.

**Comment by fenix-hub** [comment]
Thank you very much.
Fixing this little issue now
