### ISSUE TITLE
[Bug] Darkmode resets to light on closing godot

### ISSUE THREAD

**Issue by macxb** [fenix-hub/godot-engine.github-integration#72]
**Godot Version & Plugin Version**
Godot: 3.2.3
Plugin: 1.2.2

**Description**
Darkmode resets to light on closing the project and reopening.

**Comment by fenix-hub** [comment]
Hi @macxb ,
thank you for issuing this.
510f8fbd4d152f7a79a34f9951698313abd3a057 fixes this bug, will be merged soon!

**Comment by macxb** [comment]
You reopened? Do you want me to close the issue?

**Comment by fenix-hub** [comment]
Hi @macxb ,
Don't worry about it, this issue will be closed automatically with a PR :)
