### ISSUE TITLE
[Bug] Opening repository causes infinite loading

### ISSUE THREAD

**Issue by Niasty** [fenix-hub/godot-engine.github-integration#75]
**Godot Version & Plugin Version**
Godot: *3.2.3*
Plugin: *1.2.2*

**Describe the bug**
After logging in, I tried to open a GitHub repository, it starts loading, but never finishes. The plugin worked fine for me yesterday, and it works fine on my other repository.

**Screenshots**
![v6re43eew2twerv](https://user-images.githubusercontent.com/49392377/97781082-3fd00900-1b89-11eb-888d-422f053f88f9.png)

**Comment by Niasty** [comment]
The issue fixed itself after I removed a branch from the repository, the issue could be that the branch had "#" in its name.

**Comment by fenix-hub** [comment]
Hi @Niasty ,
Thank you very much for all these information.
Can you tell me the full name of the branch that gave you issues? I'd like to investigate so that won't be a problem.
Thank you.

**Comment by Niasty** [comment]
The name of the branch was "Zeppi#1"
I hope this helps
