### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by RyanLangston** [fenix-hub/godot-engine.github-integration#87]
**Godot Version & Plugin Version**
Godot: *3.2.3*
Plugin: *x1.4.1*

**Describe the bug**
I was making a push (it was the first push to the repo) and it finished, then got stuck on loading notifications then eventually outputted error code 504 then error code 0, then kept loading that. then like 5 minutes later it starts loading notifications again and it hasn't stopped

**Screenshots**
A screenshot of Godot Editor while you are encountering this bug, or a clear screenshot of Editor/External console.
![image](https://user-images.githubusercontent.com/68302450/109376357-26ae3f00-7881-11eb-8a5a-b0118fa821d7.png)

**Comment by fenix-hub** [comment]
Hi @Dragonlord1005 ,
Let me know if this fixes your issue.
Have you tried diasbling notifications while committing?
The two operations should not conflict, but let me know anyway.
Thanks

**Comment by RyanLangston** [comment]
Umm, how do I do that?

**Comment by fenix-hub** [comment]
Click on the notification bell, click on "settings" and disable "auto update notifications"

**Comment by fenix-hub** [comment]
Hi, I'll close this issue since more than a week has passed without any response.
Feel free to open new issues if needed.
Thanks
