### ISSUE TITLE
[Bug] Stuck on "pointing large file, please wait..." for hours and never finished 

### ISSUE THREAD

**Issue by Piras314** [fenix-hub/godot-engine.github-integration#93]
**Godot Version & Plugin Version**
Godot: 3.4.2
Plugin: 1.4.3

**Describe the bug**
When I try to commit my project and all its files to my GitHub repository I get stuck on this "pointing large file, please wait..." screen for hours and it never finishes and I end up giving up. I have attached a screenshot below

**Screenshots**
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/92357316/153164901-ebfb9278-95f2-4e85-8d8b-a1900705d35d.png">

**Comment by fenix-hub** [comment]
Hi,
Due to Github's limitations, > 100MB files are automatically blocked during pushes.
Currently Godot Integration is configured to automatically work with Git LFS in order to manage large files,
however, [git lfs](https://git-lfs.github.com/) should be installed locally on your machine

**Comment by Piras314** [comment]
Thank you for your help!
